# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9eaf3f6e377d10f6143322502fa6ac4083c1af5c096fce2d5800b186f53f8868e2554f9c3caf5b156800e9a6f653418efae3636669915b348e374262f3ab0ed8

test:
  secret_key_base: d2e6be0f78a19954185dea381085d5f3996cd844c73d0c194671b725e32c218ff009be0a832b84c0d8c7fa07561dd0f08925efdc2fde3af86808ee5b7536dfc5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
